server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=utf-8
        username: root
        password: cs123456
        #type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5 # 下面为连接池的补充设置，应用到上面所有数据源中,初始化大小，最小，最大
        minIdle: 5
        maxActive: 20
        maxWait: 60000 # 配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
        maxOpenPreparedStatements: 20
    jpa:
        database: MYSQL
        show-sql: true
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapperLocations: classpath:mapper/*.xml # 映射文件所在目录
  typeAliasesPackage: com.tillo.rtc.model # 程序所在目录
##pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql